services:
  postgres:
    image: postgres:16
    container_name: jessval-postgres
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: RiEiJu2509@@
      POSTGRES_DB: paqueteria

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - system-network

networks:
  system-network:
    name: system-network
    driver: bridge

volumes:
  postgres_data:
    driver: local