
services:
  system-ms-customer:
    image: juancrespo25/ms-customer-app
    container_name: system-ms-customer
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_SYNC: ${DB_SYNC}
      DB_LOG: ${DB_LOG}
      DB_POOL_SIZE: ${DB_POOL_SIZE}
    restart: always
    ports:
      - "4002:4002"
    networks:
      - system-network

networks:
  system-network:
    external: true
